version: '3.8'
services:
  backend:
    build: ./BACKEND  # Update the path to where your Node.js app's Dockerfile is located
    ports:
      - "3000:3000"  # Changed from 5000 to 3000 to reflect common Node.js defaults
    environment:
      - DATABASE_URL=postgresql://user:password@db/yourdbname  # This might not be necessary if you configure DB connections within your Node.js app
    depends_on:
      - db
    volumes:
      - ./BACKEND:/app
    networks:
      - mynetwork

  frontend:
    build:
      context: ./FRONTEND  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
