"""Initial migration.

Revision ID: 84d490cd479e
Revises: 
Create Date: 2024-03-28 17:11:35.320564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d490cd479e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('temperature', sa.String(length=20), nullable=False),
    sa.Column('precipitation', sa.String(length=20), nullable=False),
    sa.Column('soil_moisture', sa.String(length=20), nullable=False),
    sa.Column('winds', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environmental_data')
    # ### end Alembic commands ###
